donations/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'donations'
urlpatterns = [
     path('', TemplateView.as_view(template_name="donations/index.html"), name='homepage'),
     path('logout/', views.logout_view, name='logout'),
     path('donationlist/', views.DonationsListView.as_view(), name="donation_list"),
     path('donationform/', views.donationform, name = "donationform"),
     path('donationlist/saveform', views.saveform, name = "saveform"),
     path('donationlist/<int:pk>/remove', views.DeleteDonationFormView.as_view(), name='delete_donation'),
     path('makedonation/<int:pk>', views.MakeDonationView.as_view(), name="makedonation"),
     path('<int:id>/charge/', views.charge, name='charge'),
     path('success/<int:arg1>/<str:arg2>/<int:arg3>/', views.successMsg, name="success"),
     path('volunteer-post/', views.volunteerform, name='volunteer-post'),
     path('volunteer-list/', views.VolunteerListView.as_view(), name='volunteer-list'),
     path('volunteer-list/edit/<int:pk>', views.UpdateVolunteerFormView.as_view(), name='update_volunteering'),
     path('volunteer-list/<int:pk>/remove', views.DeleteVolunteerFormView.as_view(), name='delete_volunteering'),
     path('signup/<int:id>', views.signup, name='signup'),
     path('<int:pk>', views.DeleteUserVolunteer.as_view(), name='delete_user_volunteer'),
]

mdmv/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('donations.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

donations/models.py
import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from django.db import models
from django.db import models
from django.utils import timezone

# Create your models here.
class Donation(models.Model):
    name = models.CharField(max_length=50, default = "")
    description = models.CharField(max_length=500, default = "")
    goal = models.IntegerField(default = 0)
    total = models.IntegerField(default = 0)
    end_date = models.DateField(default = datetime.date.today)
    creator = models.CharField(max_length=50, default = "")

    def date_in_future(self):
        now = timezone.now()
        return now <= self.end_date

class UserDonation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_donation", null=True)
    name = models.CharField(max_length=50, default = "")
    amount = models.IntegerField(default = 0)

class VolunteerPost(models.Model):
    title = models.TextField(default = "", max_length=50)
    name = models.TextField(default = "", max_length=50)
    date = models.DateField(default = datetime.date.today)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    description = models.TextField(default = "") 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def date_in_future(self):
        now = timezone.now()
        return now <= self.date

    def end_time_after_start_time(self):
        return self.start_time < self.end_time

    def clean(self):
        if(self.start_time > self.end_time):
            raise ValidationError('Start time should be earlier than End time')
        return super().clean()

class UserVolunteer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_volunteer", null=True)
    title = models.TextField(default = "", max_length=50)
    date = models.DateField(default = datetime.date.today)
    start_time = models.TimeField(default = timezone.now)
    end_time = models.TimeField(default = timezone.now)

donations/forms.py
from .models import VolunteerPost
from django import forms

class VolunteerForm(forms.ModelForm):
    class Meta:
        model = VolunteerPost
        fields = ('title', 'name', 'date', 'start_time', 'end_time', 'description')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: Rake Leaves'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'date' : forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'xx/xx/20xx'}),
            'start_time' : forms.TimeInput(attrs={'class': 'form-control', 'placeholder': '00:00-23:59'}),
            'end_time' : forms.TimeInput(attrs={'class': 'form-control', 'placeholder': '00:00-23:59'}),
            'description' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Job description here...'}),
        }

donations/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView
from django.http import JsonResponse
from django.utils import timezone

from .forms import VolunteerForm

from .models import Donation, VolunteerPost, UserDonation, UserVolunteer

import stripe

stripe.api_key = "sk_test_51HelJXIC2I2MvSECp2y3PQgivhTUNzwM8CuqoYOpmTgUsqsqHZwitXuaqpkQYliH1C6VM8kvaB2HLdrGHkncousZ00wWWrZ4uk"

def logout_view(request):
    logout(request)
    return redirect("donations:homepage")

class DonationsView(generic.ListView):
    template_name = 'donations/donation_form.html'
    context_object_name = 'donation_list'
    def get_queryset(self):
        return Donation.objects.filter()

class MakeDonationView(generic.ListView):
    template_name = 'donations/makedonation.html'
    context_object_name = 'donation'
    def get_queryset(self, *args, **kwargs):
        return Donation.objects.filter(id=self.kwargs['pk'])

class DonationForm(forms.ModelForm):
    class Meta:
        model= Donation
        fields= ["name", "description", "goal", "end_date"]
        exclude = ["creator"]

class UserDonationForm(forms.ModelForm):
    class Meta:
        model= UserDonation
        fields = ["name", "amount"]

def donationform(request):
    form = DonationForm(request.POST or None)
    if form.is_valid():
        donation = form.save(commit = False)
        donation.creator = request.user
        donation.save()
        return HttpResponseRedirect(reverse('donations:donation_list'))
    context = {'form': form}
    return render(request, 'donations/donation_form.html', context)

def saveform(response):
    return HttpResponseRedirect(reverse('donations:homepage'))

class DeleteDonationFormView(generic.DeleteView):
    model = Donation
    template_name = 'donations/delete_donation.html'

    def get_success_url(self):
        return reverse('donations:donation_list')

class DonationsListView(generic.ListView):
    template_name = 'donations/donation_list.html'
    context_object_name = 'donation_list'
    def get_queryset(self):
        return Donation.objects.filter(
            end_date__gte=timezone.now(), 
        )

def charge(request, id):
    if request.method == 'POST':
        donation = get_object_or_404(Donation, pk=id)
        print('Data:', request.POST)
        amount = int(request.POST['amount'])
        donation.total += amount
        donation.save()

        log = UserDonation(name=donation.name, amount=amount)
        log.save()
        request.user.user_donation.add(log)

        customer = stripe.Customer.create(
            email=request.POST['email'],
            name=request.POST['name'],
            source=request.POST['stripeToken']
            )
        charge = stripe.Charge.create(
            customer=customer,
            amount=amount*100,
            currency='usd',
            description="Donation"
            )
        return redirect(reverse('donations:success', args=[amount, donation.name, donation.total]))


def successMsg(request, arg1, arg2, arg3):
	amount, name, total = arg1, arg2, arg3
	return render(request, 'donations/success.html', {'amount':amount, 'name':name, 'total':total})

def volunteerform(request):
    form = VolunteerForm(request.POST or None)
    if form.is_valid():
        opportunity = form.save(commit = False)
        opportunity.user = request.user
        opportunity.save()
        return HttpResponseRedirect(reverse('donations:volunteer-list'))
    context = {'form': form}
    return render(request, 'donations/volunteer_post.html', context)

class UpdateVolunteerFormView(generic.UpdateView):
    model = VolunteerPost
    form_class = VolunteerForm
    template_name = 'donations/update_volunteering.html'

    def get_success_url(self):
        return reverse('donations:volunteer-list')

class DeleteVolunteerFormView(generic.DeleteView):
    model = VolunteerPost
    template_name = 'donations/delete_volunteering.html'

    def get_success_url(self):
        return reverse('donations:volunteer-list')

class VolunteerListView(generic.ListView):
    template_name = 'donations/volunteer_list.html'
    context_object_name = 'volunteer_opportunities'

    def get_queryset(self):
        return VolunteerPost.objects.filter(
            date__gte=timezone.now(), 
            # date__lte=timezone.now() + timezone.timedelta(days=100),
        )

class UserVolunteerForm(forms.ModelForm):
    class Meta:
        model= VolunteerPost
        fields = ["title", "start_time", "end_time", "date"]
    
    def get_queryset(self):
        # return UserVolunteer.objects.values_list('title', flat=True).distinct()
        return UserVolunteer.objects.order_by('date').values_list('title').distinct()

def signup(request, id):
    if request.method == 'POST':
        opportunity = get_object_or_404(VolunteerPost, pk=id)

        log = UserVolunteer(title=opportunity.title, start_time=opportunity.start_time, end_time=opportunity.end_time, date=opportunity.date)
        log.save()
        request.user.user_volunteer.add(log)

        return redirect(reverse('donations:homepage'))
    return HttpResponseRedirect(reverse('donations:volunteer-list'))

class DeleteUserVolunteer(generic.DeleteView):
    model = UserVolunteer
    template_name = 'donations/delete_user_volunteer.html'

    def get_success_url(self):
        return reverse('donations:homepage')

donations/templates/donations/delete_donation.html
{% extends 'donations/base.html' %}
{% block content %}
    <br><br><br>
    <div class='header text-center'>
        <h3>Are you sure you want to delete this donation request?</h3>
   
        <br>
    <div class='form-group'>
        <form method='post'>
            {% csrf_token %}
            <button class='btn btn-danger' style="margin-right:10px">Delete</button>
            <a href="{% url 'donations:donation_list' %}" class='btn btn-dark' style="margin-left:10px">Cancel</a>
        </form>
    </div>
    
    </div>
{% endblock %}

donations/templates/donations/donation_form.html
{% extends 'donations/base.html' %}
{% block content %}

<br>

<div class="d-flex justify-content-center">
<h2>Post a Donation Request</h2>
</div>

<br>
<form action="{% url 'donations:donationform' %}" method="post">
    {% csrf_token %}
	<div class="d-flex justify-content-center">
	<label><Strong>Name of Donation:</Strong></label>
	</div>
	<div class="d-flex justify-content-center">
	<input type="text" name="name" size="30">
	</div>
    <br> <br>
    <div class="d-flex justify-content-center">
    <label><Strong>Donation Goal ($):</Strong></label>
    </div>
    <div class="d-flex justify-content-center">
    <input type="number" name="goal" size="30">
    </div>
    <br> <br>
    <div class="d-flex justify-content-center">
    <label><Strong>Donation End Date:</Strong></label>
    </div>
    <div class="d-flex justify-content-center">
    <input type="date" name="end_date">
    </div>
    <br><br>
	<div class="d-flex justify-content-center">
	<label><Strong>Description:</Strong></label> 
	</div>
	<div class="d-flex justify-content-center">
	<textArea type="text" name="description" rows="10" cols="50" wrap="hard"></textArea>
    </div>
	<br> <br>
	<div class="d-flex justify-content-center">
	<button type="submit" class="btn btn-dark">Post Donation Request</button>
	</div>
</form>
<br>

{% endblock %}

donations/templates/donations/donation_list.html
{% extends 'donations/base.html' %}
{% block content %}

<br>

<div class="d-flex justify-content-center"> <h1>Donations</h1> </div>
{% if user.is_authenticated %}
  <br><br>
  <div class="d-flex justify-content-center"> <a class="btn btn-dark" href="/donationform" role="button">Post Donation Request</a> </div>
{% endif %}

<br>

    {% if donation_list %}
        {% for donation in donation_list %}
        <div class="d-flex justify-content-center">
        <div class="card" style="width: 40rem;">
            <div class="card-header">
              <div class='float-left'>
              End Date: {{donation.end_date}} <br>
              Posted By: {{donation.creator}}
              </div>
              {% if user.is_authenticated %}
              {% if user.username == donation.creator %} 
              <div class='float-right'>            
                <a href="{% url 'donations:delete_donation' donation.pk %}" class ="btn btn-danger">Delete</a>
              </div>  
              {% endif %}
              {% endif %}
            </div>
            <div class="card-body">
              <h5 class="card-title">{{donation.name}}</h5>
              <p class="card-text">{{donation.description}}</p>
              <h6>Goal: ${{donation.goal}}</a> <br>
              <h6>Total Money Received: ${{donation.total}}</a> 
                <br><br>
                {% if user.is_authenticated %}
                  <a href="{% url 'donations:makedonation' donation.pk %}" class="btn btn-success">Donate</a>
                {% endif %}
              </div>
          </div>
        </div>
        <br>
    {% endfor %}
    
    {% else %}
      <p>No Donation Requests have been posted yet</p>
	  {% endif %}
 


<br>

{% endblock %}

donations/templates/donations/index.html
{% extends 'donations/base.html' %}
{% block content %}

{% load static %}

{% load socialaccount %}
<html>
    <head>
        <title>Please Log In Before Proceeding</title>
    </head>
    <body>
        {% if user.is_authenticated %}
        <div class="container">
            <br>
            <div align="center">
                <div class="card border-dark mb-3" style="width: 60rem;">
                    <h2 class="card-header">{{ user.username }}</h2>
                    <div class="card-body">
                      <h4 class="card-title">Welcome to your homepage!</h4>
                      <p class="card-text"><blockquote class="blockquote text-left">
                      <p class="mb-0">"The unselfish effort to bring cheer to others will be the beginning of a happier life for ourselves."</p>
                        <footer class="blockquote-footer text-center"><cite title="Source Title">Helen Keller</cite></footer>
                      </blockquote>
                      <br>
                      </p>
                      <a href="{% url 'donations:donation_list' %}" class="btn btn-dark" style="margin-right:20px">Start Donating</a>
                      <a href="{% url 'donations:volunteer-list' %}" class="btn btn-dark" style="margin-left:20px">Start Volunteering</a>
                    </div>
                  </div>
            </div>
            <br>
        </div>
        <br>
        <div class='container'>
            <div class='row'>
            <div class='col'>
            <div align='center'>    
                <h4>Your Donations</h4>
            </div>
            <br>
            {% if user.user_donation %}
                {% for item in user.user_donation.all %}
                <div class="d-flex justify-content-center">
                    <div class="card" style="width: 20rem;">
                        <div class="card-header">
                            {{item.name}}
                        </div>
                        <div class="card-body">
                          <p class="card-text">Donated ${{item.amount}}</p>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
            {% endif %}
            </div>
        <div class='col'>
            <div align='center'>    
                <h4>Volunteer Activities List</h4>
            </div>
            <br>
            {% if user.user_volunteer %}
                {% for item in user.user_volunteer.all %}
                <div class="d-flex justify-content-center">
                    <div class="card" style="width: 20rem;">
                        <div class="card-header">
                            {{item.title}}
                        </div>
                        <div class="card-body">
                          <p class="card-text">Date: {{item.date}} </p>
                          <p class="card-text">Time: {{item.start_time}} to {{item.end_time}}</p>
                          <a href="{% url 'donations:delete_user_volunteer' pk=item.id %}" class='btn btn-danger'>Remove</a>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
            {% endif %}
        </div>
        </div>
        </div>
        {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'donations/style.css' %}">
        <div align='center'>
            <h1>Welcome to the Make a Change Donation Platform!</h2>
                <br><br><br>
                <a href="{% provider_login_url 'google' %}" class="btn btn-dark" role="button">Login with Google to Proceed</a>
                <br>
                <img src="{% static 'donations/images/donate.gif' %}" style="width:300px;height:400px;">
        </div>

        {% endif %}

    </body>
</html>

{% endblock %}

donations/templates/donations/makedonation.html
{% extends 'donations/base.html' %}
{% block content %}

	<style type="text/css">
		/**
		 * The CSS shown here will not be introduced in the Quickstart guide, but shows
		 * how you can use CSS to style your Element's container.
		 */
		.StripeElement {
		  box-sizing: border-box;

		  height: 40px;

		  padding: 10px 12px;

		  border: 1px solid transparent;
		  border-radius: 4px;
		  background-color: white;

		  box-shadow: 0 1px 3px 0 #babec4;
		  -webkit-transition: box-shadow 150ms ease;
		  transition: box-shadow 150ms ease;
		}

		.StripeElement--focus {
		  box-shadow: 0 1px 3px 0 #5e6063;
		}

		.StripeElement--invalid {
		  border-color: #fa755a;
		}

		.StripeElement--webkit-autofill {
		  background-color: #fefde5 !important;
		}
	</style>





	

	<div id="container">
		<br>
		<div class = "d-flex justify-content-center">
		<div class="card border-dark mb-3 text-center" style="width: 50rem;">
			<div class="card-header">
				{% for item in donation %}
				<h2>{{item.name}}</h2>
				{% endfor %}
			</div>
			<div class="card-body">
			  <h5 class="card-title">
				{% for item in donation %}
				<h5>Goal: ${{item.goal}}</h5>  
				{% endfor %}
			  </h5>
			  <p class="card-text">
				{% for item in donation %}
				<h5>Total Received: ${{item.total}}</h5>  
				{% endfor %}
			  </p>
			</div>
		  </div>
		</div>

        <div class="d-flex justify-content-center" >
			<div style="clear:left"></div>
			<!-- Add form here -->
			{% for item in donation %}
			<form action="{% url 'donations:charge' item.pk %}" method="post" id="payment-form">
			{% endfor %}
				{% csrf_token %}
				<br>
				<br>
				<div class="form-field-12">
					<label for="amount">Choose Amount:</label>
					<select required name="amount" id="amount">
					  <option value="1">$1</option>
					  <option selected value="5">$5</option>
					  <option value="10">$10</option>
					  <option value="15">$15</option>
					  <option value="20">$20</option>
					  <option value="30">$30</option>
					</select>
				</div>
				<br>
				<label>Email</label>:
				<div class="form-field-6">
					
					<input required type="text" name="email" value={{user.email}}>
				</div>
				<br>
				<label>Name</label>:
				<div class="form-field-6">
					<input required type="text" name="name" value={{user.username}}>
				</div>
		</div>
		<div class="d-flex justify-content-left" style="margin: 50px 200px 0px 200px">
		<label for="card-element">
			Credit or Debit Card
		</label>
		</div>
			  <div class="d-flex justify-content-center" style="margin: 0px 200px 50px 200px">

				<div id="card-element" class ="form-control">
				  <!-- A Stripe Element will be inserted here. -->
				</div>

				<!-- Used to display form errors. -->
				<div id="card-errors" role="alert"></div>
			  </div>
			  
			  <div style="clear:left"></div>

            <div class= "d-flex justify-content-center">
				<input  class="btn btn-success" type="submit" value="Submit Payment" name="">
			</div>
			<br><br><br>

			</form>

			<script src="https://js.stripe.com/v3/"></script>
			

	</div>






	<script>
		// Create a Stripe client.
		var stripe = Stripe('pk_test_51HelJXIC2I2MvSEC16CzdJjIHKHZM0qKidy6X9deFBCGsgWzAs8PSHp87d5BYy8fcQkWCy1YVgmBPqNhPlH5pIRv00HnHFmGob');

		// Create an instance of Elements.
		var elements = stripe.elements();

		// Custom styling can be passed to options when creating an Element.
		// (Note that this demo uses a wider set of styles than the guide below.)
		var style = {
		  base: {
		    color: '#32325d',
		    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		    fontSmoothing: 'antialiased',
		    fontSize: '16px',
		    '::placeholder': {
		      color: '#aab7c4'
		    }
		  },
		  invalid: {
		    color: '#fa755a',
		    iconColor: '#fa755a'
		  }
		};

		// Create an instance of the card Element.
		var card = elements.create('card', {style: style});

		// Add an instance of the card Element into the `card-element` <div>.
		card.mount('#card-element');

		// Handle real-time validation errors from the card Element.
		card.addEventListener('change', function(event) {
		  var displayError = document.getElementById('card-errors');
		  if (event.error) {
		    displayError.textContent = event.error.message;
		  } else {
		    displayError.textContent = '';
		  }
		});

		// Handle form submission.
		var form = document.getElementById('payment-form');
		form.addEventListener('submit', function(event) {
		  event.preventDefault();

		  stripe.createToken(card).then(function(result) {
		    if (result.error) {
		      // Inform the user if there was an error.
		      var errorElement = document.getElementById('card-errors');
		      errorElement.textContent = result.error.message;
		    } else {
		      // Send the token to your server.
		      stripeTokenHandler(result.token);
		    }
		  });
		});

		// Submit the form with the token ID.
		function stripeTokenHandler(token) {
		  // Insert the token ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeToken');
		  hiddenInput.setAttribute('value', token.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
	</script>

{% endblock %}

donations/templates/donations/makedonation1.html
{% extends 'donations/base.html' %}
{% block content %}

<br>
<style type="text/css">
	.StripeElement {
	  box-sizing: border-box;

	  height: 40px;

	  padding: 10px 12px;

	  border: 1px solid transparent;
	  border-radius: 4px;
	  background-color: white;

	  box-shadow: 0 1px 3px 0 #e6ebf1;
	  -webkit-transition: box-shadow 150ms ease;
	  transition: box-shadow 150ms ease;
	}

	.StripeElement--focus {
	  box-shadow: 0 1px 3px 0 #cfd7df;
	}

	.StripeElement--invalid {
	  border-color: #fa755a;
	}

	.StripeElement--webkit-autofill {
	  background-color: #fefde5 !important;
	}
</style>


<script src="https://js.stripe.com/v3/"></script>


<div class="d-flex justify-content-center">
<h2>Make a Donation</h2>
</div>
<br>

<form action="{% url 'donations:charge' %}" method="post" id="payment-form">
    {% csrf_token %}
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>



<script>
	// Create a Stripe client.
	var stripe = Stripe('pk_test_51HelJXIC2I2MvSEC16CzdJjIHKHZM0qKidy6X9deFBCGsgWzAs8PSHp87d5BYy8fcQkWCy1YVgmBPqNhPlH5pIRv00HnHFmGob');

	// Create an instance of Elements.
	var elements = stripe.elements();

	// Custom styling can be passed to options when creating an Element.
	// (Note that this demo uses a wider set of styles than the guide below.)
	var style = {
	  base: {
		color: '#32325d',
		fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		fontSmoothing: 'antialiased',
		fontSize: '16px',
		'::placeholder': {
		  color: '#aab7c4'
		}
	  },
	  invalid: {
		color: '#fa755a',
		iconColor: '#fa755a'
	  }
	};

	// Create an instance of the card Element.
	var card = elements.create('card', {style: style});

	// Add an instance of the card Element into the `card-element` <div>.
	card.mount('#card-element');

	// Handle real-time validation errors from the card Element.
	card.on('change', function(event) {
	  var displayError = document.getElementById('card-errors');
	  if (event.error) {
		displayError.textContent = event.error.message;
	  } else {
		displayError.textContent = '';
	  }
	});

	// Handle form submission.
	var form = document.getElementById('payment-form');
	form.addEventListener('submit', function(event) {
	  event.preventDefault();

	  stripe.createToken(card).then(function(result) {
		if (result.error) {
		  // Inform the user if there was an error.
		  var errorElement = document.getElementById('card-errors');
		  errorElement.textContent = result.error.message;
		} else {
		  // Send the token to your server.
		  stripeTokenHandler(result.token);
		}
	  });
	});

	// Submit the form with the token ID.
	function stripeTokenHandler(token) {
	  // Insert the token ID into the form so it gets submitted to the server
	  var form = document.getElementById('payment-form');
	  var hiddenInput = document.createElement('input');
	  hiddenInput.setAttribute('type', 'hidden');
	  hiddenInput.setAttribute('name', 'stripeToken');
	  hiddenInput.setAttribute('value', token.id);
	  form.appendChild(hiddenInput);

	  // Submit the form
	  form.submit();
	}
</script>

{% endblock %}

donations/templates/donations/update_volunteering.html
{% extends 'donations/base.html' %}
{% block content %}

<h1>Update Volunteering Opportunity Post</h1>
<br><br>

<div class='form-group'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn btn-primary'>Update</button>
    </form>
</div>

{% endblock %}

donations/templates/donations/volunteer_list.html
{% extends 'donations/base.html' %}
{% block content %}

{% load static %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'donations/volunteering.css' %}"> -->

<html>
    <body>
      <br>
      <div class="d-flex justify-content-center"> <h1>Volunteering Opportunities</h1> </div>
      {% if user.is_authenticated %}
        <br><br>
        <div class="d-flex justify-content-center"> <a class="btn btn-dark" href="/volunteer-post" role="button">Post an Opportunity</a> </div>
      {% endif %}
        <br>

        {% if volunteer_opportunities %}
          {% for opportunity in volunteer_opportunities %}
            <div class="d-flex justify-content-center">
            <div class="card" style="width: 40rem;">
                <div class="card-header">
                <div class='float-left'>
                  <h6>Volunteer Job Title: {{ opportunity.title }}</h6>
                  <h6>Posted by: {{ opportunity.name }}</h6> 
                </div>
                  {% if user.is_authenticated %}
                    {% if user.id == opportunity.user.id %}
                    <div class='float-right'>
                      <a href="{% url 'donations:update_volunteering' opportunity.pk %}" class="btn btn-primary">Edit</a>
                      <a href="{% url 'donations:delete_volunteering' opportunity.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                    {% endif %}
                  {% endif %}
              </div>
                <div class="card-body">
                  <body class="card-title">
                   <h6> Date: {{ opportunity.date }} </h6>
                    <h6>Time: {{ opportunity.start_time }} to {{ opportunity.end_time }} </h6>
                  </body>
                  <br>
                  <p class="card-text">
                    <h6>Job Description:</h6>
                    {{ opportunity.description }}
                  </p>
                    {% if user.is_authenticated %}
                      <form action="{% url 'donations:signup' opportunity.pk %}" method="post">
                        {% csrf_token %}
                        <button type='submit' class="btn btn-success">Sign Up</button>
                      </form>
                    {% endif %}
                  </div>
              </div>
            </div>
            <br>
        {% endfor %}
        
      {% else %}
        <p>No Volunteering Opportunities have been posted yet</p>
      {% endif %}



    </body>
</html>
 
{% endblock %}